[[main]]
  name = "Near Me Messaging"
  url = "/nearme/setup/0-intro_video/"
  weight = 10


[[main]]
  name = "SeaX"
  url = "/seax/seax_intro/01-introduction/"
  weight = 10


[[main]]
  name = "SeaVoice"
  url = "/seavoice/tts_panel/tutorial_en/"
  weight = 20

[[social]]
  name = "Contact"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-mail"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>'
  url = "https://docs.google.com/forms/d/e/1FAIpQLSfFXRa-A1z91vQZ6Xs2FtrSTc2AFpZ97U5SWBYlpsIW5T-yrg/viewform"
  weight = 30

[[social]]
  name = "LinkedIn"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-linkedin"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"></path><rect x="2" y="9" width="4" height="12"></rect><circle cx="4" cy="4" r="2"></circle></svg>'
  url = "https://www.linkedin.com/company/seasalt-ai/"
  post = "v0.1.0"
  weight = 20

[[social]]
  name = "Home"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>'
  url = "https://seasalt.ai/"
  weight = 10


# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
